### ISSUE TITLE
RFE: Consider providing Ansible role

### ISSUE THREAD

**Issue by myllynen** [performancecopilot/pcp#595]
For discussion:

Consider PCP deployment approach one level above pcp-zeroconf: it would be nice to use an Ansible playbook which would install PCP in a certain way and for a wanted use case, for example with logging and/or a certain set of clients and/or certain PMDAs all setup for the purpose and the setup could be described with generic terms like "analysis", "frequency", "coverage" (which could accept something like Kubernetes or Java or virtualization or such).

The rationale is that people working in complex projects where even Kubernetes or a virtualization platform are only pieces of a larger puzzle have their hands so full with everything else that it is often impossible for them to become familiar with domain-specific details and terminology (PMNS? pmlogconf? PMDA? pmlogger? PMCD? pmrep? PMAPI?) so using something that can be at least to certain extent considered as lingua franca could be very helpful. (https://github.com/linux-system-roles/metrics is somewhat related but it seems there hasn't been much progress on that front recently.)

A made up example how this could look like as an Ansible playbook:

```
- hosts: all
  become: true
  tasks:
    - name: Deploy PCP for Hyper-Converged Virtualization Host | Development Environment
      pcp:
        state: running
        acl: false
        components:
          - analysis
          - documentation
          - forward
          - logging
          - web
        analysis:
          legacy_apps: false
          x_apps: false
        forward:
          type: elasticsearch
          target: https://192.168.122.122:9200/
          metrics:
            - kvm
            - gluster
            - libvirt
           space_scale: kB
        logging:
          remote: false
          frequency: 1min
          coverage: complete
          compress: true
          scope:
            - gluster
            - os-default
            - virtualization
          retention: 7days
        web:
          allow_access:
            - 192.168.122.0/255.255.255.0
            - 10.10.10.10
          authentication: false
```

**Comment by myllynen** [comment]
This might be best implemented as a system role - compare to:

```
---
- hosts: rhel7.5-test
  vars:
    network_connections:
      - name: DBnic
        state: up
        type: ethernet
        interface_name: eth1
        autoconnect: yes
        ip:
          dhcp4: yes
          auto6: no
  roles:
    - role: rhel-system-roles.network
```
